
# 3.2.3 Уход от циклов: обработка данных с применением массивов

## Задание 1

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` из ```12``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте две матрицы размера ```(3,4)``` с порядком следования элементов в стиле С и Fortran. Найдите поэлементное произведение этих матриц, а после - максимальный элемент в полученной матрице. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```25```)



**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного целочисленного массива ndarray из 12 элементов на отрезке [0,10]
array = np.random.randint(0, 11, size=12)

# Вывод созданного массива
print("Массив:")
print(array)

# Создание матрицы размера (3,4) в стиле C
matrix_c = array.reshape((3, 4), order='C')

# Вывод матрицы в стиле C
print("\nМатрица в стиле C:")
print(matrix_c)

# Создание матрицы размера (3,4) в стиле Fortran
matrix_f = array.reshape((3, 4), order='F')

# Вывод матрицы в стиле Fortran
print("\nМатрица в стиле Fortran:")
print(matrix_f)

# Поэлементное произведение матриц
elementwise_product = np.multiply(matrix_c, matrix_f)

# Вывод матрицы с поэлементным произведением
print("\nМатрица с поэлементным произведением:")
print(elementwise_product)

# Нахождение максимального элемента в полученной матрице
max_element = np.max(elementwise_product)

# Вывод максимального элемента
print("\nМаксимальный элемент в полученной матрице:", max_element)


Массив:
[ 3  7  7  0  1  0  9  8  9  4 10 10]

Матрица в стиле C:
[[ 3  7  7  0]
 [ 1  0  9  8]
 [ 9  4 10 10]]

Матрица в стиле Fortran:
[[ 3  0  9  4]
 [ 7  1  8 10]
 [ 7  0  9 10]]

Матрица с поэлементным произведением:
[[  9   0  63   0]
 [  7   0  72  80]
 [ 63   0  90 100]]

Максимальный элемент в полученной матрице: 100


## Задание 2

**Условие:**
Создайте ```3``` случайных целочисленных массива ```ndarray``` размера ```(10,10)``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте из данных массивов один трехмерный массив. Найдя размер полученного массива, вычислите количество элементов в нем. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```56```)


**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание трех случайных целочисленных массивов ndarray размера (10,10) элементов на отрезке [0,10]
array1 = np.random.randint(0, 11, size=(10, 10))
array2 = np.random.randint(0, 11, size=(10, 10))
array3 = np.random.randint(0, 11, size=(10, 10))

# Объединение массивов в трехмерный массив
three_dimensional_array = np.array([array1, array2, array3])

# Вывод размера полученного трехмерного массива
print("Размер трехмерного массива:", three_dimensional_array.shape)

# Вычисление количества элементов в трехмерном массиве
total_elements = three_dimensional_array.size

# Вывод количества элементов в трехмерном массиве
print("Количество элементов в трехмерном массиве:", total_elements)


Размер трехмерного массива: (3, 10, 10)
Количество элементов в трехмерном массиве: 300


## Задание 3

**Условие:**
С использование методов ```ndarray``` сформируйте массив размера ```(20,2)```, в первом столбце которого идут целые числа, начиная с ```1```,а во втором - первые 20 нечетных чисел, начиная с ```3```. Найдите среднее значение второго столбца.

**Формат ответа:**
Число (например, ```34```)



**Решение:**

In [ ]:
import numpy as np

# Создаем массив размера (20, 2)
array = np.zeros((20, 2), dtype=int)

# Заполняем первый столбец числами от 1 до 20
array[:, 0] = np.arange(1, 21)

# Заполняем второй столбец первыми 20 нечетными числами, начиная с 3 (арифметическая прогрессия)
array[:, 1] = 2 * np.arange(1, 21) + 1

# Находим среднее значение второго столбца
mean_second_column = np.mean(array[:, 1])

# Выводим массив и среднее значение второго столбца
print("Массив:")
print(array)
print("\nСреднее значение второго столбца:", mean_second_column)



Массив:
[[ 1  3]
 [ 2  5]
 [ 3  7]
 [ 4  9]
 [ 5 11]
 [ 6 13]
 [ 7 15]
 [ 8 17]
 [ 9 19]
 [10 21]
 [11 23]
 [12 25]
 [13 27]
 [14 29]
 [15 31]
 [16 33]
 [17 35]
 [18 37]
 [19 39]
 [20 41]]

Среднее значение второго столбца: 22.0
