
# 3.2.2 Индексирование и вырезание

## Задание 1

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` из ```1000``` элементов, принадлежащих интервалу ```[2,10]```. С помощью булевой индексации найдите все простые элементы в массиве. Найдите сумму полученных элементов. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```94```)



**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного целочисленного массива ndarray из 1000 элементов на интервале [2,10]
array = np.random.randint(2, 11, size=1000)

# Вывод созданного массива
print("Массив:")
print(array)

# Функция для определения простого числа
def is_prime(n):
    if n <= 1:
        return False
    elif n <= 3:
        return True
    elif n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Булевая индексация для поиска всех простых элементов
prime_elements = array[np.array([is_prime(x) for x in array])]

# Нахождение суммы простых элементов
sum_prime_elements = np.sum(prime_elements)

# Вывод простых элементов и их суммы
print("\nПростые элементы:")
print(prime_elements)
print("\nСумма простых элементов:", sum_prime_elements)


Массив:
[ 5  9  9  2  3  2 10  6  6  6  4 10  4  6  4  7  7  6  2  6  4  7  6  9
  2  6  9  3  2  4  3  9  3  7  8  7  9 10 10  4  4  8  5  5  8  7 10  6
  3  2  3 10 10  2  4  5  8  4  7 10  7  8  8  9  8  5  6 10  3  5  9  4
  2  6  6  3  8  7  3  6  3  9  6  7  2  8  4  9  2 10  2  7  5  2  6  5
  5  5  8  6  9  4  6  6  4  6  3  4  5  2  7  4  3  2  8 10  8  3  3  2
 10  6  4  4  3 10  4  2  3  3  3  5  8  6  8 10  3  5  7  2  3  3  8  7
  3  3 10  9  5  5  2  4  2  4 10  7  5  4  7  5  9  5  6  6  2  8  6  9
  7  2  9  7  8  5 10  9  2  4  5  5  9  3  8  5  6  4 10  5  2  2  3  5
  6  7  9  6  4  3  6  4  5 10  5  5  9  8 10  9  8  2  6  9  9  7 10 10
  6  9  7  5  3  8 10  4  8  8  9  8 10  5  5  2  6 10  6  9 10  4  3  4
  2  4  9  4 10 10 10 10  9  5 10  7  6  5  5  8  2  5 10  9 10  3  9  7
  5  3  4  7  9  6  6  7  9 10 10  4  6  2  5  4  6  6  7  6  5  6  8  2
  7  2  2  8  8  9  8  4  9  9  7  3  3  4  8  2  4  7  5  5  7  2 10  6
  4  5  2  3  4  5 10  2  8  9  9  7  2  7 

## Задание 2

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` размера ```(10,10)``` элементов, принадлежащих отрезку ```[0,10]```. Найдите сумму квадратов элементов главной диагонали, не используя циклы. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```150```)



**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного целочисленного массива ndarray размера (10,10) элементов на отрезке [0,10]
array = np.random.randint(0, 11, size=(10, 10))

# Вывод созданного массива
print("Массив:")
print(array)

# Нахождение главной диагонали с помощью np.diag
main_diagonal = np.diag(array)

# Нахождение суммы квадратов элементов главной диагонали с помощью np.sum и np.square
sum_of_squares = np.sum(np.square(main_diagonal))

# Вывод суммы квадратов элементов главной диагонали
print("\nСумма квадратов элементов главной диагонали:", sum_of_squares)


Массив:
[[ 3  7  7  0  1  0  9  8  9  4]
 [10 10  9  4  4  2  9  8  2  4]
 [ 2  5 10  5  4  0  4  2  5 10]
 [ 4  7  0  4  7  1  0  2  1  7]
 [ 1  5  6  5  7  8  8  2  2  9]
 [ 6 10 10  3  3  6  5  8  4  1]
 [ 0  9  1  8  8  0  2  9  3 10]
 [ 9  6  2  9  5  8  5  6  9  6]
 [ 7  6  3  4  8  1  3  7  2  0]
 [ 4  4  1  6  5  1  4  1  7  4]]

Сумма квадратов элементов главной диагонали: 370


## Задание 3

**Условие:**
Создайте случайный трехмерный целочисленный массив ```ndarray``` размера ```(10,10,10)``` элементов, принадлежащих отрезку ```[0,10]```. Напомним, что подвыборка по первой оси вида ```[0,:,:]``` является матрицей размера ```(10,10)```. Найти поэлементную сумму всех матриц, полученных описанной выше операцией среза при прохождении вдоль всей первой оси (```[0,:,:]```, ```[1,:,:]``` и т.д.). В ответе укажите максимальный элемент в получившейся матрице. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```50```)



**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного трехмерного целочисленного массива ndarray размера (10,10,10) элементов на отрезке [0,10]
array = np.random.randint(0, 11, size=(10, 10, 10))

# Вывод созданного массива
print("Массив:")
print(array)

# Выполнение суммирования по первой оси с помощью np.sum
sum_along_first_axis = np.sum(array, axis=0)

# Вывод результата суммирования
print("\nСумма всех матриц по первой оси:")
print(sum_along_first_axis)

# Нахождение максимального элемента в получившейся матрице
max_element = np.max(sum_along_first_axis)

# Вывод максимального элемента
print("\nМаксимальный элемент в получившейся матрице:", max_element)


Массив:
[[[ 3  7  7  0  1  0  9  8  9  4]
  [10 10  9  4  4  2  9  8  2  4]
  [ 2  5 10  5  4  0  4  2  5 10]
  [ 4  7  0  4  7  1  0  2  1  7]
  [ 1  5  6  5  7  8  8  2  2  9]
  [ 6 10 10  3  3  6  5  8  4  1]
  [ 0  9  1  8  8  0  2  9  3 10]
  [ 9  6  2  9  5  8  5  6  9  6]
  [ 7  6  3  4  8  1  3  7  2  0]
  [ 4  4  1  6  5  1  4  1  7  4]]

 [[ 5  0  6  2  9  7  0 10  8  0]
  [ 5  3  0  4  3  3  3  6  4  7]
  [ 2  4  4  2  4  1  2  3  9  0]
  [ 5  2  1  0  6  8  9  6  1  1]
  [ 0  8  4  2  2  1 10  8  2  0]
  [ 1  1  1  3  6  4  6  8  1  9]
  [ 3 10  5  0 10  1  1  6  9 10]
  [ 5  1  1  8  7  3  3  9  0  2]
  [ 0  2  8 10  5  3  2  5  3  7]
  [ 3  4  9  4 10 10  0  6  4  7]]

 [[ 5  0  7  9  5  6 10  3  9 10]
  [ 8  7  0  2  3  3  7  1  6  3]
  [ 4  2  8  3  0  0  1  3  4  5]
  [ 7  9  4  2  1  4  2  3  8  3]
  [ 3  7  6  9  9  8 10  7  6  0]
  [ 4  7  7  5  8  8  4  7  9  5]
  [ 3 10  1  6  8  2  6 10  6  7]
  [ 6  8 10  3 10  3  0  4  8 10]
  [ 4  7  9  8  2  1 10  2  0 10]
  