
# 3.2.1 Быстрые поэлементные операции над массивами

## Задание 1

**Условие:**
Создайте произвольный массив ```ndarray``` из 10 элементов типа ```float16```. Присутствие ненулевых дробных частей у элементов обязательно. С использованием методов ```numpy``` отделите дробные части элементов и найдите их среднее значение.

**Формат ответа:**
Число (например, ```0.2```)


**Решение:**

In [ ]:
import numpy as np

# Создание произвольного массива ndarray из 10 элементов типа float16
array = np.random.uniform(low=0.1, high=10, size=10).astype(np.float16)

# Вывод созданного массива
print("Исходный массив:")
print(array)

# Отделение дробных частей элементов
fractional_parts = np.modf(array)[0]

# Вывод дробных частей элементов
print("\nДробные части элементов:")
print(fractional_parts)

# Нахождение среднего значения дробных частей элементов
mean_fractional_parts = np.mean(fractional_parts)

# Вывод среднего значения дробных частей элементов
print("\nСреднее значение дробных частей элементов:", mean_fractional_parts)


Исходный массив:
[4.97  8.17  1.124 6.06  7.613 9.45  5.645 4.82  3.562 2.457]

Дробные части элементов:
[0.9688 0.1719 0.124  0.0586 0.6133 0.4531 0.6445 0.8203 0.5625 0.457 ]

Среднее значение дробных частей элементов: 0.4873


## Задание 2

**Условие:**
Создайте два произвольных целочисленных массива ```ndarray``` длины ```10``` и найдите количество позиций, в которых значения первого массива в ```3``` раза больше(не строго) значений второго массива при поэлементном сравнивании.

**Формат ответа:**
Число (например, ```5```)



**Решение:**

In [ ]:
import numpy as np

# Создание двух произвольных целочисленных массивов ndarray длины 10
array1 = np.random.randint(0, 100, size=10)
array2 = np.random.randint(0, 100, size=10)

# Вывод созданных массивов
print("Первый массив:")
print(array1)
print("\nВторой массив:")
print(array2)

# Поэлементное сравнение массивов и нахождение количества позиций, где значения первого массива в 3 раза больше значений второго массива
count = np.sum(array1 >= 3 * array2)

# Вывод количества позиций
print("\nКоличество позиций, где значения первого массива в 3 раза больше значений второго массива:", count)


Первый массив:
[47 39 22  0 41 81 77 28 98 27]

Второй массив:
[92  7 38 97 34 89 61 44 82 28]

Количество позиций, где значения первого массива в 3 раза больше значений второго массива: 1


## Задание 3

**Условие:**
Создайте массив ```ndarray``` длины ```20``` типа ```float16``` и с использованием методов numpy, найдите среднее и среднеквадратическое отклонение **по формулам**(np.mean и np.std можно использовать только для проверки результатов): для массива $\{x_i\}$

*   $\mu = \frac{1}{n}(x_1 + ... x_n) $
*   $\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_i-\mu)^2}$

**Формат ответа:**
Кортеж из 2х чисел (например, ```(3.2, 5.1)```)



**Решение:**

In [ ]:
import numpy as np

# Создание массива ndarray длины 20 типа float16
array = np.random.uniform(low=0.1, high=10, size=20).astype(np.float16)

# Вывод созданного массива
print("Массив:")
print(array)

# Нахождение среднего значения
mean_value = np.mean(array)

# Расчет среднеквадратического отклонения по формуле
std_dev = np.sqrt(np.mean((array - mean_value) ** 2))

# Вывод результатов
print("\nСреднее значение (проверка):", mean_value)
print("Среднеквадратическое отклонение (проверка):", std_dev)

# Проверка результатов с использованием np.mean и np.std
print("\nСреднее значение (проверка с использованием np.mean):", np.mean(array))
print("Среднеквадратическое отклонение (проверка с использованием np.std):", np.std(array))



Массив:
[4.75    2.432   3.44    8.766   8.04    9.64    0.11426 8.195   6.297
 0.8228  5.2     1.57    1.302   8.16    8.45    6.766   5.145   9.03
 7.766   9.58   ]

Среднее значение (проверка): 5.773
Среднеквадратическое отклонение (проверка): 3.088

Среднее значение (проверка с использованием np.mean): 5.773
Среднеквадратическое отклонение (проверка с использованием np.std): 3.088
