
# 3.2.2 Индексирование и вырезание

## Задание 1

Конечно, давайте создадим аналогичную задачу без использования изображения.

**Условие:**
Создайте целочисленный массив `ndarray` размера `(3,3)`. Представьте, что каждый элемент этого массива находится на черной позиции, как показано на следующей схеме:

```
B  W  B
W  B  W
B  W  B
```

Теперь, используя индексы элементов на черных позициях (B), выполните 4 выборки элементов согласно следующим выражениям:

1. Выборка элементов с индексами `(0, 0)`, `(1, 1)`, `(2, 2)`.
2. Выборка элементов с индексами `(0, 2)`, `(1, 1)`, `(2, 0)`.
3. Выборка элементов с индексами `(0, 1)`, `(1, 1)`, `(2, 1)`.
4. Выборка элементов с индексами `(1, 0)`, `(1, 1)`, `(1, 2)`.

Найдите максимальное значение в каждой из полученных выборок.

**Формат ответа:**
Кортеж чисел (например, `(3, 5, 2, 6)`).

**Решение:**

In [ ]:
import numpy as np

# Создание целочисленного массива ndarray размера (3,3)
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Вывод созданного массива
print("Массив:")
print(array)

# Создание массива с черными позициями (B)
black_positions = np.array([[True, False, True],
                            [False, True, False],
                            [True, False, True]])

# Получение индексов черных позиций
black_indices = np.argwhere(black_positions)

# Выборка элементов по заданным индексам
samples_indices = [
    [(0, 0), (1, 1), (2, 2)],
    [(0, 2), (1, 1), (2, 0)],
    [(0, 1), (1, 1), (2, 1)],
    [(1, 0), (1, 1), (1, 2)]
]

# Выполнение выборки и нахождение максимального значения для каждой выборки
for i, indices in enumerate(samples_indices):
    sample = array[tuple(zip(*indices))]
    max_value = np.max(sample)
    print(f"\nВыборка {i + 1}:")
    print(sample)
    print(f"Максимальное значение: {max_value}")


Массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Выборка 1:
[1 5 9]
Максимальное значение: 9

Выборка 2:
[3 5 7]
Максимальное значение: 7

Выборка 3:
[2 5 8]
Максимальное значение: 8

Выборка 4:
[4 5 6]
Максимальное значение: 6


## Задание 2

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` из ```100``` элементов, принадлежащих отрезку ```[0,10]```. С помощью булевой индексации найдите все четные элементы в массиве. Найдите сумму полученных элементов. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```56```)

**Оценка в баллах:** 3 балла

**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного целочисленного массива ndarray из 100 элементов на отрезке [0,10]
array = np.random.randint(0, 11, size=100)

# Вывод созданного массива
print("Массив:")
print(array)

# Булевая индексация для поиска всех четных элементов
even_elements = array[array % 2 == 0]

# Нахождение суммы четных элементов
sum_even_elements = np.sum(even_elements)

# Вывод четных элементов и их суммы
print("\nЧетные элементы:")
print(even_elements)
print("\nСумма четных элементов:", sum_even_elements)


Массив:
[ 3  7  7  0  1  0  9  8  9  4 10 10  9  4  4  2  9  8  2  4  2  5 10  5
  4  0  4  2  5 10  4  7  0  4  7  1  0  2  1  7  1  5  6  5  7  8  8  2
  2  9  6 10 10  3  3  6  5  8  4  1  0  9  1  8  8  0  2  9  3 10  9  6
  2  9  5  8  5  6  9  6  7  6  3  4  8  1  3  7  2  0  4  4  1  6  5  1
  4  1  7  4]

Четные элементы:
[ 0  0  8  4 10 10  4  4  2  8  2  4  2 10  4  0  4  2 10  4  0  4  0  2
  6  8  8  2  2  6 10 10  6  8  4  0  8  8  0  2 10  6  2  8  6  6  6  4
  8  2  0  4  4  6  4  4]

Сумма четных элементов: 266


## Задание 3

**Условие:**
Создайте случайный целочисленный массив ndarray размера ```(10,10)``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте подвыборку по всем строкам с нечетным индексом. Найдите сумму всех элементов в полученной матрице. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```150```)

**Оценка в баллах:** 4 балла


**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного целочисленного массива ndarray размера (10,10) элементов на отрезке [0,10]
array = np.random.randint(0, 11, size=(10, 10))

# Вывод созданного массива
print("Массив:")
print(array)

# Подвыборка по всем строкам с нечетным индексом
subarray = array[1::2]

# Нахождение суммы всех элементов в полученной матрице
sum_subarray = np.sum(subarray)

# Вывод подвыборки и суммы её элементов
print("\nПодвыборка по всем строкам с нечетным индексом:")
print(subarray)
print("\nСумма всех элементов в полученной матрице:", sum_subarray)


Массив:
[[ 3  7  7  0  1  0  9  8  9  4]
 [10 10  9  4  4  2  9  8  2  4]
 [ 2  5 10  5  4  0  4  2  5 10]
 [ 4  7  0  4  7  1  0  2  1  7]
 [ 1  5  6  5  7  8  8  2  2  9]
 [ 6 10 10  3  3  6  5  8  4  1]
 [ 0  9  1  8  8  0  2  9  3 10]
 [ 9  6  2  9  5  8  5  6  9  6]
 [ 7  6  3  4  8  1  3  7  2  0]
 [ 4  4  1  6  5  1  4  1  7  4]]

Подвыборка по всем строкам с нечетным индексом:
[[10 10  9  4  4  2  9  8  2  4]
 [ 4  7  0  4  7  1  0  2  1  7]
 [ 6 10 10  3  3  6  5  8  4  1]
 [ 9  6  2  9  5  8  5  6  9  6]
 [ 4  4  1  6  5  1  4  1  7  4]]

Сумма всех элементов в полученной матрице: 253
