
# 3.2.4 Математические и статистические операции

## Задание 1

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` размера ```(15,15)``` элементов, принадлежащих отрезку ```[1,10]```. С помощью методов булевых массивов найдите количество элементов в полученном массиве, которые являются полными квадратами. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```4```)


**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного целочисленного массива ndarray размера (15,15) элементов на отрезке [1,10]
array = np.random.randint(1, 11, size=(15, 15))

# Вывод созданного массива
print("Исходный массив:")
print(array)

# Создание булевого массива, где True обозначает полные квадраты, а False - остальные числа
perfect_squares_mask = np.sqrt(array) % 1 == 0

# Нахождение количества элементов, являющихся полными квадратами, с помощью метода np.sum()
count_perfect_squares = np.sum(perfect_squares_mask)

# Вывод количества элементов, являющихся полными квадратами
print("\nКоличество элементов, являющихся полными квадратами:", count_perfect_squares)


Исходный массив:
[[ 4  8  8  1  2  1 10  9 10  5 10  5  5  3 10]
 [ 9  3  5  3  6  6  5  1  5  3  6  5  8  1  5]
 [ 8  2  1  3  2  8  2  6  7  6  8  9  9  3  3]
 [10  7  4  4  7  6  9  5  2  1 10  2  9  9  1]
 [ 3 10  4 10  7  3 10  6  9  6  7 10  7  8  7]
 [ 4  5  9  2  4  8  3  1  5  5  2  7  6  2  5]
 [ 2  8  5  6  1  7  3 10  8  1  9  1  6  4  1]
 [ 5  4  4  4  7  5  8  3  5  5  3  5  2  3  4]
 [10  1  6  3  2  1  7  9 10  7  2  2  1  9  5]
 [ 3  3  2  9  3  1  2  2  2  4  7  5  7  9  2]
 [10  4  6  1  2  2  7 10  6  2  2  9  8  4  4]
 [10  1  3  1  3  9  6  4  3  6  4  8  4  5 10]
 [ 5  1  7  5  8  6  1  8 10  6  7  4 10  9  8]
 [ 1  3  4  4  8  2  7  4  5  3  9  4  1  1  2]
 [ 4  5  6  8 10  5  3  2  5  3  4  9  4  4  8]]

Количество элементов, являющихся полными квадратами: 70


## Задание 2

**Условие:**
Напишите функцию, которая принимает на вход квадратную матрицу, возводит ее в степень ```100``` и находит ее определитель. Если определитель отличен от нуля, то функция возвращает определитель матрицы, которая является обратной к транспанированной исходной матрице, иначе - ноль. Проверьте работоспособность на матрице, указанной в пункте решение.

**Формат ответа:**
Число (например, ```2.7```)



**Решение:**

In [ ]:
example_matrix = np.array([[2,5,7],
                        [6,3,4],
                        [5,-2,-3]])

In [ ]:
import numpy as np

def determinant_and_inverse_power(matrix):
    # Возводим матрицу в степень 100
    powered_matrix = np.linalg.matrix_power(matrix, 100)

    # Находим определитель возведенной матрицы
    det = np.linalg.det(powered_matrix)

    # Если определитель не равен нулю, то матрица обратима
    if det != 0:
        # Находим обратную матрицу к транспонированной исходной матрице
        inverse_matrix = np.linalg.inv(matrix.T)
        return det, inverse_matrix
    else:
        return 0


determinant, inverse_matrix = determinant_and_inverse_power(example_matrix)

print("Определитель матрицы, возведенной в степень 100:", determinant)
if determinant != 0:
    print("Обратная матрица к транспонированной исходной матрице:")
    print(inverse_matrix)
else:
    print("Определитель матрицы равен нулю, обратная матрица не существует.")


Определитель матрицы, возведенной в степень 100: 1.9635743770999456e+56
Обратная матрица к транспонированной исходной матрице:
[[  1. -38.  27.]
 [ -1.  41. -29.]
 [  1. -34.  24.]]


## Задание 3

**Условие:**
Создайте два случайных массива длины ```100```, первый из которых является выборкой из нормального распределения, а второй - равномерного распределения на полуинтервале ```[0,1)```. Найдите абсолютные значения разности средних и среднеквадратических отклонений у полученных массивов.

**Формат ответа:**
Кортеж чисел (например, ```(2.7, 0.0)```)




**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание выборки из нормального распределения (среднее = 0, стандартное отклонение = 1)
normal_array = np.random.normal(loc=0, scale=1, size=100)

# Создание выборки из равномерного распределения на полуинтервале [0,1)
uniform_array = np.random.uniform(low=0, high=1, size=100)

# Нахождение среднего и стандартного отклонения для каждого массива
mean_normal = np.mean(normal_array)
mean_uniform = np.mean(uniform_array)
std_normal = np.std(normal_array)
std_uniform = np.std(uniform_array)

# Нахождение абсолютных значений разности средних и среднеквадратических отклонений
abs_mean_difference = np.abs(mean_normal - mean_uniform)
abs_std_difference = np.abs(std_normal - std_uniform)

print("Абсолютная разность средних значений:", abs_mean_difference)
print("Абсолютная разность среднеквадратических отклонений:", abs_std_difference)


Абсолютная разность средних значений: 0.4217422212730742
Абсолютная разность среднеквадратических отклонений: 0.7258934713780913
