
# 3.2.4 Математические и статистические операции

## Задание 1

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` размера ```(10,10)``` элементов, принадлежащих отрезку ```[0,10]```. С помощью методов ```np.mean()``` и ```np.std()``` центрируйте и нормируйте элементы в столбцах. Найдите разброс полученных значений в полученной матрице. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Кортеж чисел (например, ```(-0.45,0.89)```)



**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного целочисленного массива ndarray размера (10,10) элементов на отрезке [0,10]
array = np.random.randint(0, 11, size=(10, 10))

# Вывод созданного массива
print("Исходный массив:")
print(array)

# Центрирование элементов в столбцах (вычитание среднего по столбцу)
centered_array = array - np.mean(array, axis=0)

# Нормирование элементов в столбцах (деление на стандартное отклонение по столбцу)
normalized_array = centered_array / np.std(array, axis=0)

# Вывод массива после центрирования и нормирования
print("\nМассив после центрирования и нормирования:")
print(normalized_array)

# Нахождение разброса (дисперсии) значений в полученной матрице
variance = np.var(normalized_array)

# Вывод разброса
print("\nРазброс значений в полученной матрице:", variance)


Исходный массив:
[[ 3  7  7  0  1  0  9  8  9  4]
 [10 10  9  4  4  2  9  8  2  4]
 [ 2  5 10  5  4  0  4  2  5 10]
 [ 4  7  0  4  7  1  0  2  1  7]
 [ 1  5  6  5  7  8  8  2  2  9]
 [ 6 10 10  3  3  6  5  8  4  1]
 [ 0  9  1  8  8  0  2  9  3 10]
 [ 9  6  2  9  5  8  5  6  9  6]
 [ 7  6  3  4  8  1  3  7  2  0]
 [ 4  4  1  6  5  1  4  1  7  4]]

Массив после центрирования и нормирования:
[[-0.50495552  0.04944682  0.55945325 -2.         -1.92506684 -0.86204366
   1.44148324  0.89950042  1.62229492 -0.4472136 ]
 [ 1.70422489  1.53285135  1.09226586 -0.33333333 -0.5500191  -0.2234928
   1.44148324  0.89950042 -0.84641474 -0.4472136 ]
 [-0.82055272 -0.93948954  1.35867217  0.08333333 -0.5500191  -0.86204366
  -0.31642315 -1.0993894   0.21160368  1.34164079]
 [-0.18935832  0.04944682 -1.30539091 -0.33333333  0.82502865 -0.54276823
  -1.72274826 -1.0993894  -1.19908755  0.4472136 ]
 [-1.13614993 -0.93948954  0.29304694  0.08333333  0.82502865  1.69215977
   1.08990196 -1.0993894  -0.846414

## Задание 2

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` размера ```(15,15)``` элементов, принадлежащих отрезку ```[0,10]```. С помощью методов булевых массивов найдите количество четных элементов в полученном массиве. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```56```)


**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного целочисленного массива ndarray размера (15,15) элементов на отрезке [0,10]
array = np.random.randint(0, 11, size=(15, 15))

# Вывод созданного массива
print("Исходный массив:")
print(array)

# Создание булевого массива, где True обозначает четные элементы и False - нечетные
even_mask = array % 2 == 0

# Нахождение количества четных элементов с помощью метода np.sum()
even_count = np.sum(even_mask)

# Вывод количества четных элементов
print("\nКоличество четных элементов в полученном массиве:", even_count)


Исходный массив:
[[ 3  7  7  0  1  0  9  8  9  4 10 10  9  4  4]
 [ 2  9  8  2  4  2  5 10  5  4  0  4  2  5 10]
 [ 4  7  0  4  7  1  0  2  1  7  1  5  6  5  7]
 [ 8  8  2  2  9  6 10 10  3  3  6  5  8  4  1]
 [ 0  9  1  8  8  0  2  9  3 10  9  6  2  9  5]
 [ 8  5  6  9  6  7  6  3  4  8  1  3  7  2  0]
 [ 4  4  1  6  5  1  4  1  7  4  5  0  6  2  9]
 [ 7  0 10  8  0  5  3  0  4  3  3  3  6  4  7]
 [ 2  4  4  2  4  1  2  3  9  0  5  2  1  0  6]
 [ 8  9  6  1  1  0  8  4  2  2  1 10  8  2  0]
 [ 1  1  1  3  6  4  6  8  1  9  3 10  5  0 10]
 [ 1  1  6  9 10  5  1  1  8  7  3  3  9  0  2]
 [ 0  2  8 10  5  3  2  5  3  7  3  4  9  4 10]
 [10  0  6  4  7  5  0  7  9  5  6 10  3  9 10]
 [ 8  7  0  2  3  3  7  1  6  3  4  2  8  3  0]]

Количество четных элементов в полученном массиве: 124


## Задание 3

**Условие:**
Напишите функцию, которая принимает на вход квадратную матрицу и находит ее определитель. Если определитель отличен от нуля, то функция возвращает определитель матрицы, которая является обратной к транспанированной исходной матрице, иначе выдает ноль. Проверьте работоспособность на матрице, указанной в пункте решение.

**Формат ответа:**
Число (например, ```2.7```)




**Решение:**

In [ ]:
example_matrix = np.array([[2,5,7],
                        [6,3,4],
                        [5,-2,-3]])

In [ ]:
import numpy as np

def determinant_and_inverse(matrix):
    # Находим определитель исходной матрицы
    det = np.linalg.det(matrix)

    # Если определитель не равен нулю, то матрица обратима
    if det != 0:
        # Находим обратную матрицу к транспонированной исходной матрице
        inverse_matrix = np.linalg.inv(matrix.T)
        return det, inverse_matrix
    else:
        return 0



determinant, inverse_matrix = determinant_and_inverse(example_matrix)

print("Определитель матрицы:", determinant)
if determinant != 0:
    print("Обратная матрица к транспонированной исходной матрице:")
    print(inverse_matrix)
else:
    print("Определитель матрицы равен нулю, обратная матрица не существует.")


Определитель матрицы: -1.0000000000000284
Обратная матрица к транспонированной исходной матрице:
[[  1. -38.  27.]
 [ -1.  41. -29.]
 [  1. -34.  24.]]
